
import { GLAccount } from '@/types/accounting';

export const predefinedGlAccounts: GLAccount[] = [
  { id: '1', code: '5705', name: 'Access Cards Keys', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '2', code: '2100', name: 'Accounts Payable', category: 'Liabilities', type: 'Liability', isActive: true },
  { id: '3', code: '1200', name: 'Accounts Receivable', category: 'Assets', type: 'Asset', isActive: true },
  { id: '4', code: '1654', name: 'Accumulated Depreciation', category: 'Assets', type: 'Asset', isActive: true },
  { id: '5', code: '5000', name: 'Admin Expenses', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '6', code: '4130', name: 'Admin Fee', category: 'Revenue', type: 'Income', isActive: true },
  { id: '7', code: '1205', name: 'Allowance for Bad Debt', category: 'Assets', type: 'Asset', isActive: true },
  { id: '8', code: '6134', name: 'Amenity Center Cleaning', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '9', code: '5212', name: 'Amenity Center R & M', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '10', code: '5050', name: 'Amenity Center Supplies', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '11', code: '4012', name: 'ARC Deposit', category: 'Revenue', type: 'Income', isActive: true },
  { id: '12', code: '4550', name: 'Architectural Project Fee', category: 'Revenue', type: 'Income', isActive: true },
  { id: '13', code: '5025', name: 'Architectural Review', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '14', code: '4000', name: 'Assessment', category: 'Revenue', type: 'Income', isActive: true },
  { id: '15', code: '8040', name: 'Audit & Tax Expense', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '16', code: '5010', name: 'Bank Charges', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '17', code: '4025', name: 'Builder Fee Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '18', code: '1600', name: 'Building', category: 'Assets', type: 'Asset', isActive: true },
  { id: '19', code: '1102', name: 'CD-X1349', category: 'Assets', type: 'Asset', isActive: true },
  { id: '20', code: '4131', name: 'Certified Mail Fee', category: 'Revenue', type: 'Income', isActive: true },
  { id: '21', code: '5731', name: 'Cleaning/Janitorial Supplies', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '22', code: '4515', name: 'Clubhouse Rental Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '23', code: '9020', name: 'Contingency Fund', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '24', code: '9050', name: 'Contribution to Reserves', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '25', code: '4050', name: 'Contribution to Reserves Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '26', code: '8010', name: 'D&O Insurance', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '27', code: '5035', name: 'Delinquency Fees', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '28', code: '4115', name: 'Demand Letter Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '29', code: '2500', name: 'Due To/Due From', category: 'Liabilities', type: 'Liability', isActive: true },
  { id: '30', code: '6220', name: 'Electric', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '31', code: '5220', name: 'Electrical R&M', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '32', code: '5071', name: 'Electronic Storage', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '33', code: '1652', name: 'Entrance Monuments', category: 'Assets', type: 'Asset', isActive: true },
  { id: '34', code: '4155', name: 'Facility Rentals', category: 'Revenue', type: 'Income', isActive: true },
  { id: '35', code: '5215', name: 'Fence Repairs', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '36', code: '5045', name: 'Fire Extinguisher / Inspection', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '37', code: '1015', name: 'First Citizens Bank Capital Improvement-X96', category: 'Assets', type: 'Asset', isActive: true },
  { id: '38', code: '1000', name: 'First Citizens Bank Operating-X2806', category: 'Assets', type: 'Asset', isActive: true },
  { id: '39', code: '1100', name: 'First Citizens Bank Reserve-X7393', category: 'Assets', type: 'Asset', isActive: true },
  { id: '40', code: '1651', name: 'Fixtures', category: 'Assets', type: 'Asset', isActive: true },
  { id: '41', code: '5012', name: 'Flagpole', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '42', code: '6015', name: 'Force Mow', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '43', code: '4133', name: 'Force Mow', category: 'Revenue', type: 'Income', isActive: true },
  { id: '44', code: '4035', name: 'Force Mow', category: 'Revenue', type: 'Income', isActive: true },
  { id: '45', code: '3502', name: 'Fund Balance Operating', category: 'Equity', type: 'Equity', isActive: true },
  { id: '46', code: '3504', name: 'Fund Balance Reserve', category: 'Equity', type: 'Equity', isActive: true },
  { id: '47', code: '1650', name: 'Furniture', category: 'Assets', type: 'Asset', isActive: true },
  { id: '48', code: '4021', name: 'Gate Opener Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '49', code: '5210', name: 'Gate R&M', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '50', code: '8000', name: 'General Liability', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '51', code: '5200', name: 'General Repairs & Maintenance', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '52', code: '5706', name: 'Holiday Decorating', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '53', code: '5235', name: 'HVAC', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '54', code: '8001', name: 'Insurance - Workers Comp', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '55', code: '4015', name: 'Insurance Assessment', category: 'Revenue', type: 'Income', isActive: true },
  { id: '56', code: '4100', name: 'Interest Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '57', code: '1399', name: 'Interfund Receivable', category: 'Assets', type: 'Asset', isActive: true },
  { id: '58', code: '1500', name: 'Investment Account', category: 'Assets', type: 'Asset', isActive: true },
  { id: '59', code: '5700', name: 'Irrigation R&M', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '60', code: '6240', name: 'Irrigation Utility', category: 'Expenses', type: 'Expense', isActive: true },
  // Adding more accounts from the image...
  { id: '61', code: '5910', name: 'Janitorial Contract', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '62', code: '4505', name: 'Key Fob Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '63', code: '4506', name: 'Land Sale Proceeds', category: 'Revenue', type: 'Income', isActive: true },
  { id: '64', code: '5715', name: 'Landscape Upgrades', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '65', code: '5920', name: 'Landscaping Contract', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '66', code: '4110', name: 'Late Charge Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '67', code: '4137', name: 'Late Fee Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '68', code: '4026', name: 'Late Fee Interest', category: 'Revenue', type: 'Income', isActive: true },
  { id: '69', code: '4105', name: 'Legal Charge Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '70', code: '5214', name: 'Lighting R & M', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '71', code: '4060', name: 'Lot Sale Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '72', code: '5030', name: 'Management Fee', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '73', code: '5040', name: 'Meeting', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '74', code: '4500', name: 'Misc Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '75', code: '3999', name: 'Net Income (Loss)', category: 'Equity', type: 'Equity', isActive: true },
  { id: '76', code: '3000', name: 'Opening Balance Equity', category: 'Equity', type: 'Equity', isActive: true },
  { id: '77', code: '2200', name: 'Owner Refund', category: 'Liabilities', type: 'Liability', isActive: true },
  { id: '78', code: '2010', name: 'Owner Refunds Due', category: 'Liabilities', type: 'Liability', isActive: true },
  { id: '79', code: '4510', name: 'Pavilion Rental', category: 'Revenue', type: 'Income', isActive: true },
  { id: '80', code: '5085', name: 'Pending Receipt', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '81', code: '5720', name: 'Pest Control Expense', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '82', code: '6230', name: 'Phone/Internet', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '83', code: '5780', name: 'Playground R&M', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '84', code: '5230', name: 'Plumbing R&M', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '85', code: '5760', name: 'Pond Maintenance', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '86', code: '5525', name: 'Pool Chemicals', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '87', code: '5921', name: 'Pool Cleaning Contract Expense', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '88', code: '5734', name: 'Pool Monitor', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '89', code: '5055', name: 'Pool Permit', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '90', code: '5736', name: 'Pool Repair', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '91', code: '5060', name: 'Postage', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '92', code: '2000', name: 'Prepaid Assessments', category: 'Liabilities', type: 'Liability', isActive: true },
  { id: '93', code: '1300', name: 'Prepaid Expenses', category: 'Assets', type: 'Asset', isActive: true },
  { id: '94', code: '1305', name: 'Prepaid Insurance', category: 'Assets', type: 'Asset', isActive: true },
  { id: '95', code: '2202', name: 'Prepaid Misc Income', category: 'Liabilities', type: 'Liability', isActive: true },
  { id: '96', code: '2205', name: 'Prepaid Owner Transfer', category: 'Liabilities', type: 'Liability', isActive: true },
  { id: '97', code: '1310', name: 'Prepaid Taxes', category: 'Assets', type: 'Asset', isActive: true },
  { id: '98', code: '5056', name: 'Professional Fees: Legal', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '99', code: '5046', name: 'Professional Fees: Legal Collections', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '100', code: '8030', name: 'Property Tax', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '101', code: '4033', name: 'Rent Common Area', category: 'Revenue', type: 'Income', isActive: true },
  { id: '102', code: '5199', name: 'Reserve Study', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '103', code: '3500', name: 'Retained Earnings', category: 'Equity', type: 'Equity', isActive: true },
  { id: '104', code: '4120', name: 'Returned Payment Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '105', code: '5240', name: 'Roofing R&M', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '106', code: '5930', name: 'Security Patrol Contract', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '107', code: '5735', name: 'Security System Monitoring', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '108', code: '5730', name: 'Signage', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '109', code: '5015', name: 'Social Coordinator', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '110', code: '5014', name: 'Social Events', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '111', code: '1653', name: 'Solar Lights', category: 'Assets', type: 'Asset', isActive: true },
  { id: '112', code: '4010', name: 'Special Assessment', category: 'Revenue', type: 'Income', isActive: true },
  { id: '113', code: '5070', name: 'Storage Unit', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '114', code: '4135', name: 'Transfer Fee', category: 'Revenue', type: 'Income', isActive: true },
  { id: '115', code: '6250', name: 'Trash', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '116', code: '4020', name: 'Utilities Income', category: 'Revenue', type: 'Income', isActive: true },
  { id: '117', code: '4125', name: 'Violation Fines', category: 'Revenue', type: 'Income', isActive: true },
  { id: '118', code: '6260', name: 'Water & Sewer', category: 'Expenses', type: 'Expense', isActive: true },
  { id: '119', code: '4140', name: 'Working Capital Contribution', category: 'Revenue', type: 'Income', isActive: true },
];
